// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProductManagementAPI.Model.Context;

#nullable disable

namespace ProductManagementAPI.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    [Migration("20260520162622_Initial Create")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.27")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProductManagementAPI.Model.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Price")
                        .HasColumnType("real");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1001,
                            Brand = "Apple",
                            Description = "The Best Phone in the World",
                            Name = "iPhone",
                            Price = 79000f,
                            Quantity = 100
                        },
                        new
                        {
                            Id = 1002,
                            Brand = "Apple",
                            Description = "The Best Laptop in the World",
                            Name = "MacBook Air",
                            Price = 119000f,
                            Quantity = 100
                        },
                        new
                        {
                            Id = 1003,
                            Brand = "Apple",
                            Description = "The Best Tablet in the World",
                            Name = "iPad",
                            Price = 59000f,
                            Quantity = 100
                        },
                        new
                        {
                            Id = 1004,
                            Brand = "Apple",
                            Description = "The Best PC in the World",
                            Name = "iMac",
                            Price = 149000f,
                            Quantity = 100
                        },
                        new
                        {
                            Id = 1005,
                            Brand = "Apple",
                            Description = "The Best Smart Watch in the World",
                            Name = "iWatch",
                            Price = 39000f,
                            Quantity = 100
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
